config/routes.rb
Rails.application.routes.draw do
  get 'doses/index'
  get 'meal_plans/index'
  get 'meal_plans/show'
  get 'meal_plans/new'
  get 'meal_plans/create'
  get 'meals/show'
  get 'deliveries/new'
  post 'deliveries/create'
  get "shop/shopping"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meal_plans do
    resources :meals, only: [:show, :update]
    resources :doses, only: [:index]
    resources :shops, only: [:new, :create]
    resources :deliveries, only: [:new, :create]
  end
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :doses, dependent: :delete_all
  has_many :meals, dependent: :delete_all

  def aisles
    aisles = []
    self.doses.each do |dose|
      aisles << dose.aisle
    end
    aisles = aisles.uniq
  end

  #returns an array of cooked meals for a meal plan
  def cooked_meals
    self.meals.where(cooked: true)
  end

  def meals_cooked_percent
    # meals cooked divided by all meal plan meals
    cooked_count = 0
    self.meals.each do |meal|
      cooked_count += 1 if meal.cooked
    end
    (cooked_count.to_f / self.meals.count.to_f * 100).to_i
  end

  def ingredients_bought_percent
    # ingredients purchased divided by all meal plan ingredients
    purchased_count = 0
    self.doses.each do |dose|
      purchased_count += 1 if dose.purchased
    end
    (purchased_count.to_f / self.doses.count.to_f * 100).to_i
  end

  def ingr_by_aisle
    ingr_by_aisle = {}
    self.aisles.each do |aisle|
      ingr_by_aisle[aisle] = Hash.new(0)
      self.doses.each do |dose|
        if dose.ingredient.aisle == aisle
          ingr_by_aisle[aisle][dose.ingredient.name] += dose.value
        end
      end
      self.doses.each do |dose|
        if dose.ingredient.aisle == aisle && ingr_by_aisle[aisle][dose.ingredient.name].class == Float
          ingr_by_aisle[aisle][dose.ingredient.name] = ingr_by_aisle[aisle][dose.ingredient.name].to_i if ingr_by_aisle[aisle][dose.ingredient.name] % 1 == 0
          ingr_by_aisle[aisle][dose.ingredient.name] = [ingr_by_aisle[aisle][dose.ingredient.name].to_s + " #{dose.unit}", dose.id]
        end
      end
    end
    ingr_by_aisle
  end

  def purchased_ingredients
    purchased_ingredients = []
    self.doses.each do |dose|
      purchased_ingredients << dose if dose.purchased?
    end
    purchased_ingredients
  end

  def self.purchased_ratio(hash)
    completed = 0
    total = hash.size
    hash.each do |_ingr_name, dose_info|
      dose = Dose.find(dose_info[1])
      completed += 1 if dose.purchased
    end
    "<span class='completed'>#{completed}</span>/<span class='total'>#{total}</span>"
  end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  include MealPlansHelper

  def index
    @meal_plans = policy_scope(MealPlan).order(created_at: :desc)
    @meals_cooked = current_user.cooked_count
  end

  def show
    @meal_plan = MealPlan.find(params[:id])
    authorize @meal_plan
    @aisles = @meal_plan.aisles
    @breakfast_meals = @meal_plan.meals.where(meal_type: 'breakfast')
    @lunch_meals = @meal_plan.meals.where(meal_type: 'lunch')
    @dinner_meals = @meal_plan.meals.where(meal_type: 'dinner')
  end

  def new
    @meal_plan = MealPlan.new
    authorize @meal_plan
  end

  def create
    @meal_plan = MealPlan.new
    authorize @meal_plan
    @meal_plan.user = current_user
    @meal_plan.save
    if params[:meal_params]
      # recipes = obtain_recipes(params[:meal_params][:calories], params[:meal_params][:diet_type], params[:meal_params][:exclusions])
      calories = params[:meal_params][:calories]
      diet_type = params[:meal_params][:diet_type]
      exclusions = "#{params[:meal_params][:exclusions]},#{params[:meal_params][:otherexclusions]}"
      @meal_plan.update(calories: calories, diet_type: diet_type, exclusions: exclusions)
      MealPlanCreationJob.perform_later(calories, diet_type, exclusions, @meal_plan.id)
      redirect_to meal_plan_path(@meal_plan)
    else
      render :new
    end
  end

  def edit
    @meal_plan = MealPlan.find(params[:id])
    authorize @meal_plan
  end

  def update
    @meal_plan = MealPlan.find(params[:id])
    authorize @meal_plan
    update_doses(params['purchased'])

    if params['commit'] == "Confirm purchases"
      dose = Dose.find(params['purchased'].keys.first)
      meal = dose.meal
      redirect_to meal_plan_meal_path(@meal_plan, meal)
    else
      redirect_to meal_plan_path(@meal_plan)
    end
  end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
  # returns an array of recipe value hashes from spoonacular
  def obtain_recipes(calories, diet_type, excluded_ingredients)
    recipes = []
    conn = Faraday.new(url: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/mealplans/generate?timeFrame=week&targetCalories=#{calories}&diet=#{diet_type}&exclude=#{excluded_ingredients}")
    conn.headers["X-RapidAPI-Host"] = "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"
    conn.headers["X-RapidAPI-Key"] = ENV['SPOONACULAR_API_KEY']
    response = conn.get
    response_data = JSON.parse(response.body)
    response_data['items'].each do |item|
      recipe_hash = JSON.parse(item['value'])
      recipe_hash['slot'] = item['slot']
      recipes << recipe_hash
    end
    recipes
  end

  def create_meals(recipes, meal_plan)
    recipes.each do |recipe|
      meal = Meal.new(title: recipe['title'].capitalize, meal_id: recipe['id'], image_url: 'default-food.jpg')
      conn = Faraday.new(url: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/#{recipe['id']}/information")
      conn.headers["X-RapidAPI-Host"] = "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"
      conn.headers["X-RapidAPI-Key"] = ENV['SPOONACULAR_API_KEY']
      response = conn.get
      response_data = JSON.parse(response.body)
      meal.image_url = response_data['image']
      meal.directions = response_data['instructions']
      meal.meal_type = meal_type(recipe['slot'])
      meal.prep_time = response_data['readyInMinutes']
      meal.meal_plan = meal_plan
      meal.save
      response_data['extendedIngredients'].each do |ext_ingr|
        unless ext_ingr['amount'].zero?
          aisle = ext_ingr['aisle'].match(/^([^;]+)/)[0]
          ingredient = Ingredient.create(name: ext_ingr['name'], aisle: aisle)
          dose = Dose.new(value: ext_ingr['amount'].round(2), unit: ext_ingr['unit'], direction: ext_ingr['originalString'])
          dose.ingredient = ingredient
          dose.meal_plan = meal_plan
          dose.meal = meal
          dose.save
        end
      end
    end
  end

  def meal_type(slot)
    return 'breakfast' if slot == 1
    return 'lunch' if slot == 2
    return 'dinner' if slot == 3
  end

  def update_doses(dose_binary_hash)
    dose_binary_hash.each do |id, binary|
      dose = Dose.find(id)
      if binary == "0"
        dose.purchased = false
      else
        dose.purchased = true
      end
      dose.save
    end
  end

  # parses recipe value hashes to extract the ids. we'll use these to search for ingredients
  def obtain_recipe_ids(recipes)
    recipe_ids = []
    recipes.each do |recipe|
      recipe_ids << recipe['id']
    end
    recipe_ids
  end

  # returns a hash of ingredient names/quantities from Spoonacular
  # requires an array of recipe ids
  def collect_ingredients_data(recipe_ids)
    ingredients = {}
    recipe_ids.each do |id|
      conn = Faraday.new(url: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/#{id}/ingredientWidget.json")
      conn.headers["X-RapidAPI-Host"] = "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"
      conn.headers["X-RapidAPI-Key"] = ENV['SPOONACULAR_API_KEY']
      response = conn.get
      response_data = JSON.parse(response.body)
      response_data['ingredients'].each do |ingredient|
        ingredients[ingredient['name']] = ingredient['amount']
      end
    end
    ingredients
  end

  def create_doses(ingredients_data, meal_plan)
    ingredients_data.each do |key, value|
      ingredient = Ingredient.find_or_create_by(name: key)
      dose = Dose.new(value: value['metric']['value'], unit: value['metric']['unit'])
      dose.ingredient = ingredient
      dose.meal_plan = meal_plan
      dose.save
    end
  end
end

app/views/meal_plans/_purchased.html.erb
  <h1 class="appear-on-load d-none">Your groceries. By aisle. 👍</h1>
      <%= simple_form_for :purchased, url:  edit_meal_plan_path(@meal_plan), method: 'patch', :html=> { class: 'ingr_form_list' } do |f| %>
        <% i = 0 %>
        <% @meal_plan.ingr_by_aisle.keys.sort.each do |aisle| %>
          <div class="ingr_parent_list col-10 col-md-9">
            <div class="aisle">
              <div><%= aisle %> <span class="ratio"> (<%= raw(MealPlan.purchased_ratio(@meal_plan.ingr_by_aisle[aisle])) %>)</span></div>
              <span class="down-caret" style="align=center;"><i class="fas fa-caret-down"></i></span></div>
          </div>
          <div class="ingr-list d-none">
            <div class="row col-10 col-md-9">
              <% @meal_plan.ingr_by_aisle[aisle].each do |ingr_name, dose_info| %>
                <%#=dose_info is an array with two elements: dose_info[0] is the dose amount as a string and dose_info[1] is the dose id %>
                <div class="col-12 col-md-6 list-item mt-3 dose" data-aisle-index=<%= "#{i}" %>>
                  <%= ingr_name.titleize %><em><%= dose_info[0] %></em>
                  <div class="purchased d-none">
                    <%= f.input dose_info[1], as: :boolean, input_html: { checked: Dose.find(dose_info[1]).purchased } %>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
          <% i += 1 %>
        <% end %>
      <% end %>

app/views/meal_plans/edit.html.erb
<head>
  <meta http-equiv="" content="3">
  <%= stylesheet_link_tag "meal_plan_show", media: 'all' %>
</head>
<div class="profile d-flex flex-column justify-content-around mt-3">
  <div class="row">
    <div class="col-12 col-md-6 d-flex flex-column align-items-center ">
      <div class="profile-photo">
        <% if current_user.photo.file.nil? %>
        <%= image_tag "default-avatar.jpg", class: "profile-avatar" %>
        <% else %>
        <%= cl_image_tag current_user.photo, class: "profile-avatar" %>
        <% end %>
      </div>
      <div class="profile-info text-center">
        <h6>name: <span class="user-info"><%= current_user.name %></span></h6>
        <h6>email: <span class="user-info"><%= current_user.email %></span></h6>
        <h6>meals cooked: <span class="user-info"><%= @meals_cooked %></span></h6>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="meal-plan-progress mx-3">
        <h2 class="text-center">Current meal plan</h2>
        <%= link_to meal_plan_path(current_user.active_plan), class: 'current-meal-plan-card-link' do %>
        <div class="current-meal-plan-card mt-4">
          <div class="current-meal-plan-info d-flex mb-3">
            <div class="diet-type-icon d-flex flex-column align-items-center">
              <% case current_user.active_plan.diet_type %>
              <% when 'Ketogenic' %>
              <%= image_tag "keto-diet.png" %>
              <%= 'Ketogenic' %>
              <% when 'Vegan' %>
              <%= image_tag "vegan-diet.png" %>
              <%= 'Vegan' %>
              <% when 'Vegetarian' %>
              <%= image_tag "vegetarian-diet.png" %>
              <%= 'Vegetarian' %>
              <% when 'Paleo' %>
              <%= image_tag "paleo-diet.png" %>
              <%= 'Paleo' %>
              <% when 'Primal' %>
              <%= image_tag "primal-diet.png" %>
              <%= 'Primal' %>
              <% when '' %>
              <div class='no-diet-type'></div>
              <%= 'Not specify' %>
              <% end %>
            </div>
            <div class="current-meal-plan-details">
              <h3><%= current_user.active_plan.created_at.strftime("%b %d, %Y") %></h3>
              <h5>Calories: <span class="meal-filter-info"><%= current_user.active_plan.calories %></span></h5>
              <h5>Allergies/ dislikes: <span class="meal-filter-info"><%= (current_user.active_plan.exclusions).split(',').join(', ').last((current_user.active_plan.exclusions).split(',').join(', ').length - 1) %></span></h5>
            </div>
          </div>
          <div class="progress-track">
            <h6>Meals cooked:</h6>
            <div class="progress mb-2">
              <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.meals_cooked_percent %>%" aria-valuenow="<%= current_user.active_plan.meals_cooked_percent %>" aria-valuemin="0" aria-valuemax="100">
                <%= current_user.active_plan.meals_cooked_percent %>%
              </div>
            </div>
            <h6>Ingredients bought:</h6>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.ingredients_bought_percent %>%" aria-valuenow="<%= current_user.active_plan.ingredients_bought_percent %>" aria-valuemin="0" aria-valuemax="100">
                <%= current_user.active_plan.ingredients_bought_percent %>%
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="user-activity d-flex align-items-center">
  <div class="col-12 col-md-12">
    <div class="cooked-meal-container mx-3">
      <h1 class="appear-on-load d-none">Your groceries. By aisle. 👍</h1>
      <%= simple_form_for :purchased, url:  edit_meal_plan_path(@meal_plan), method: 'patch', :html=> { class: 'ingr_form_list' } do |f| %>
        <% i = 0 %>
        <% @meal_plan.ingr_by_aisle.keys.sort.each do |aisle| %>
          <div class="ingr_parent_list col-10 col-md-9">
            <div class="aisle">
              <div><%= aisle %> <span class="ratio"> (<%= raw(MealPlan.purchased_ratio(@meal_plan.ingr_by_aisle[aisle])) %>)</span></div>
              <span class="down-caret" style="align=center;"><i class="fas fa-caret-down"></i></span></div>
          </div>
          <div class="ingr-list d-none">
            <div class="row col-10 col-md-9">
              <% @meal_plan.ingr_by_aisle[aisle].each do |ingr_name, dose_info| %>
                <%#=dose_info is an array with two elements: dose_info[0] is the dose amount as a string and dose_info[1] is the dose id %>
                <div class="col-12 col-md-6 list-item mt-3 dose" data-aisle-index=<%= "#{i}" %>>
                  <%= ingr_name.titleize %><em><%= dose_info[0] %></em>
                  <div class="purchased d-none">
                    <%= f.input dose_info[1], as: :boolean, input_html: { checked: Dose.find(dose_info[1]).purchased } %>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
          <% i += 1 %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<script>
  let pans = document.querySelectorAll('.loading-pan');
    let doses = document.querySelectorAll('.dose');
    let onLoadElements = document.querySelectorAll('.appear-on-load')
    if(doses.length > 0) {
      pans.forEach((pan) => {
        pan.style.display = 'none'
      });
      onLoadElements.forEach((element) => {
        element.classList.remove('d-none');
      });
    } else {
      console.log('no ingredients yet')
    }
</script>

app/views/meal_plans/index.html.erb
<head>
  <meta http-equiv="" content="3">
  <%= stylesheet_link_tag "meal_plan_show", media: 'all' %>
</head>
<div class="profile d-flex flex-column align-items-center">
  <div class="profile-photo">
    <% if current_user.photo.file.nil? %>
      <%= image_tag "default-avatar.jpg", class: "profile-avatar" %>
    <% else %>
      <%= cl_image_tag current_user.photo, class: "profile-avatar" %>
    <% end %>
  </div>
  <div class="profile-info text-center">
    <h6>name: <span class="user-info"><%= current_user.name %></span></h6>
    <h6>email: <span class="user-info"><%= current_user.email %></span></h6>
    <h6>meals cooked: <span class="user-info"><%= @meals_cooked %></span></h6>
  </div>
</div>

<div class="user-activity d-flex justify-content-around">
  <div class="row">
    <div class="col-12 col-md-5">
      <div class="meal-plan-progress mx-3">
        <h2 class="text-center">Current meal plan</h2>
        <%= link_to meal_plan_path(current_user.active_plan), class: 'current-meal-plan-card-link' do %>
          <div class="current-meal-plan-card mt-4">
            <div class="current-meal-plan-info d-flex mb-3">
              <div class="diet-type-icon d-flex flex-column align-items-center">
                <% case current_user.active_plan.diet_type %>
                <% when 'Ketogenic' %>
                <%= image_tag "keto-diet.png" %>
                <%= 'Ketogenic' %>
                <% when 'Vegan' %>
                <%= image_tag "vegan-diet.png" %>
                <%= 'Vegan' %>
                <% when 'Vegetarian' %>
                <%= image_tag "vegetarian-diet.png" %>
                <%= 'Vegetarian' %>
                <% when 'Paleo' %>
                <%= image_tag "paleo-diet.png" %>
                <%= 'Paleo' %>
                <% when 'Primal' %>
                <%= image_tag "primal-diet.png" %>
                <%= 'Primal' %>
                <% when '' %>
                <div class='no-diet-type'></div>
                <%= 'Not specify' %>
                <% end %>
              </div>
              <div class="current-meal-plan-details">
                <h3><%= current_user.active_plan.created_at.strftime("%b %d, %Y") %></h3>
                <h5>Calories: <span class="meal-filter-info"><%= current_user.active_plan.calories %></span></h5>
                <h5>Allergies/ dislikes: <span class="meal-filter-info"><%= (current_user.active_plan.exclusions).split(',').join(', ').last((current_user.active_plan.exclusions).split(',').join(', ').length - 1) %></span></h5>
              </div>
            </div>
            <div class="progress-track">
              <h6>Meals cooked:</h6>
              <div class="progress mb-2">
                <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.meals_cooked_percent %>%" aria-valuenow="<%= current_user.active_plan.meals_cooked_percent %>" aria-valuemin="0" aria-valuemax="100">
                  <%= current_user.active_plan.meals_cooked_percent %>%
                </div>
              </div>
              <h6>Ingredients bought:</h6>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.ingredients_bought_percent %>%" aria-valuenow="<%= current_user.active_plan.ingredients_bought_percent %>" aria-valuemin="0" aria-valuemax="100">
                  <%= current_user.active_plan.ingredients_bought_percent %>%
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div class="generate-new-plan d-flex justify-content-around">
          <%= link_to "Generate new meal plan", meal_plans_new_path, class: "btn btn-primary px-5"%>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-7">
      <div class="cooked-meal-container mx-3">
        <h2 class="text-center mb-4">Meals you've cooked</h2>
        <% @meal_plans.each do |plan| %>
            <% plan.cooked_meals.each do |meal| %>
                <%= link_to meal_plan_meal_path(plan, meal), class: 'cooked-meal-link' do %>
                  <div class="cooked-meal-card">
                    <%= image_tag meal.image_url %>
                    <div class="meal-info">
                      <h5><%= meal.title %></h5>
                      <p><%= plan.created_at.strftime("%b %d, %Y") %></p>
                    </div>
                  </div>
                <% end %>
             <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meal_plans/new.html.erb
<div class="container_meal_plan_new">
  <h1 class="text-center">Create new meal plan</h1>
  <div class="form_for d-flex flex-column justify-content-around">
    <div class="calories-form" style="visibility: hidden;">
      <%= simple_form_for :meal_params, url: meal_plans_path, method: :post do |f| %>
      <%= f.input :calories, label: false, placeholder: 'calories' %>
    </div>
    <div class="diet_type_icon">
      <h4>Desired calories per day</h4>
      <ul class="row meal_plan_icon d-flex justify-content-around">
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 kcal">
            <span class="icon"> <%= image_tag "1500kcal.png" %></span>
            <span class="text"><span id="calories">1500</span> Kcal</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 kcal">
            <span class="icon"> <%= image_tag "1800kcal.png" %></span>
            <span class="text"><span id="calories">1800</span> Kcal</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 kcal">
            <span class="icon"> <%= image_tag "2100kcal.png" %></span>
            <span class="text"><span id="calories">2100</span> Kcal</span>
            <span class="tooltiptext">Recommended!</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 kcal">
            <span class="icon"> <%= image_tag "2400kcal.png" %></span>
            <span class="text"><span id="calories">2400</span> Kcal</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 kcal">
            <span class="icon"> <%= image_tag "3000kcal.png" %></span>
            <span class="text"><span id="calories">3000</span> Kcal</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="diettype-form" style="visibility: hidden;">
      <%= f.input :diet_type, label: false, placeholder: 'diet type' %>
    </div>
    <div class="diet_type_icon">
      <h4>Browse by diet (optional)</h4>
      <ul class="row meal_plan_icon d-flex justify-content-around">
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 type">
            <span class="icon"> <%= image_tag "keto-diet.png" %></span>
            <span class="text" id="type-name">Ketogenic</span>
            <span class="tooltiptext">High-fat, very low carb</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 type">
            <span class="icon"> <%= image_tag "vegan-diet.png" %></span>
            <span class="text" id="type-name">Vegan</span>
            <span class="tooltiptext">No animal-derived ingredients</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 type">
            <span class="icon"> <%= image_tag "vegetarian-diet.png" %></span>
            <span class="text" id="type-name">Vegetarian</span>
            <span class="tooltiptext">No meat</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 type">
            <span class="icon"> <%= image_tag "paleo-diet.png" %></span>
            <span class="text" id="type-name">Paleo</span>
            <span class="tooltiptext">No dairy or cereal products and processed food</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-2">
          <a href="#" class="d-flex flex-column mt-3 type">
            <span class="icon"> <%= image_tag "primal-diet.png" %></span>
            <span class="text" id="type-name">Primal</span>
            <span class="tooltiptext">Raw and minimally processed foods</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="allergy-form" style="visibility: hidden;">
      <%= f.input :exclusions, label: false, placeholder: 'Allergies' %>
    </div>
    <div class="diet_type_icon">
      <h4>Allergies (optional)</h4>
      <ul class="row meal_plan_icon d-flex justify-content-around">
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "milk-allergy.png" %></span>
            <span class="text" id="allergy">Milk</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "egg-allergy.png" %></span>
            <span class="text" id="allergy">Eggs</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "peanut-allergy.png" %></span>
            <span class="text" id="allergy">Peanuts</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "soy-allergy.png" %></span>
            <span class="text" id="allergy">Soy</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "wheat-allergy.png" %></span>
            <span class="text" id="allergy">Wheat</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "fish-allergy.png" %></span>
            <span class="text" id="allergy">Fish</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 allergies">
            <span class="icon"> <%= image_tag "shellfish-allergy.png" %></span>
            <span class="text" id="allergy">Shellfish</span>
          </a>
        </li>
        <li class="col-6 col-md-3 col-lg-1">
          <a href="#" class="d-flex flex-column mt-3 exclusion">
            <span class="icon"> <%= image_tag "more.png" %></span>
            <span class="text">Other</span>
          </a>
        </li>
      </ul>
    </div>
      <div class="exclusion-form" style="display: none;">
        <%= f.input :otherexclusions, label: false, placeholder: 'exclusions' %>
      </div>
      <%= f.submit "Plan your meal", class: "btn btn-primary mt-3" %>
    <% end %>
  </div>
</div>