config/routes.rb
Rails.application.routes.draw do
  get 'doses/index'
  get 'meal_plans/index'
  get 'meal_plans/show'
  get 'meal_plans/new'
  get 'meal_plans/create'
  get 'meals/show'
  get 'deliveries/new'
  post 'deliveries/create'
  get "shop/shopping"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meal_plans do
    resources :meals, only: [:show, :update]
    resources :doses, only: [:index]
    resources :shops, only: [:new, :create]
    resources :deliveries, only: [:new, :create]
  end
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :user
  belongs_to :meal_plan
  def delivery
    user = current_user[:id]
  end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  def show
    @deliveries = DeliveryPolicy.find(params[:id])
    authorize @delivery
  end

  def new
    @delivery = Delivery.new
    authorize @delivery
  end

  def create
    @delivery = Delivery.new(delivery_params)
    authorize @delivery
    @delivery.user = current_user
    @meal_plan = MealPlan.find(params[:meal_plan_id])
    @delivery.meal_plan = @meal_plan

    if @delivery.save
      redirect_to  edit_meal_plan_path(@meal_plan)
    else
      render :new, alert: 'Invalid information.'
    end
  end

  def update
    @meal = Delivery.find(params[:id])
    authorize @delivery

    redirect_to meal_plan_meal_path(@meal.meal_plan, @meal)
  end
  private

  def delivery_params
    ### left it at name and photo for testing purposes
    ### include all params when ready
    params.require(:delivery).permit(:address, :note, :user)
  end
end

app/views/deliveries/_form.html.erb
<%= simple_form_for @delivery, url: meal_plan_deliveries_path  do |f| %>
  <% if @delivery.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @delivery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :address, :placeholder => 'Delivery to:', class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.text_field :note, :placeholder => 'Special note:', class: 'form-control'%>
  </div>
  <%= f.submit class: 'btn btn-warning' %>

<% end %>
<br>
<br>
<br>
<br>

app/views/deliveries/new.html.erb
<head>
  <meta http-equiv="" content="3">
  <%= stylesheet_link_tag "meal_plan_show", media: 'all' %>
</head>
<div class="profile d-flex flex-column align-items-center">
  <div class="profile-photo">
    <% if current_user.photo.file.nil? %>
      <%= image_tag "default-avatar.jpg", class: "profile-avatar" %>
    <% else %>
      <%= cl_image_tag current_user.photo, class: "profile-avatar" %>
    <% end %>
  </div>
  <div class="profile-info text-center">
    <h6>name: <span class="user-info"><%= current_user.name %></span></h6>
    <h6>email: <span class="user-info"><%= current_user.email %></span></h6>
    <h6>meals cooked: <span class="user-info"><%= @meals_cooked %></span></h6>
  </div>
</div>

<div class="user-activity d-flex justify-content-around">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="meal-plan-progress mx-3">
        <h2 class="text-center">Current meal plan</h2>
        <%= link_to meal_plan_path(current_user.active_plan), class: 'current-meal-plan-card-link' do %>
          <div class="current-meal-plan-card mt-4">
            <div class="current-meal-plan-info d-flex mb-3">
              <div class="diet-type-icon d-flex flex-column align-items-center">
                <% case current_user.active_plan.diet_type %>
                <% when 'Ketogenic' %>
                <%= image_tag "keto-diet.png" %>
                <%= 'Ketogenic' %>
                <% when 'Vegan' %>
                <%= image_tag "vegan-diet.png" %>
                <%= 'Vegan' %>
                <% when 'Vegetarian' %>
                <%= image_tag "vegetarian-diet.png" %>
                <%= 'Vegetarian' %>
                <% when 'Paleo' %>
                <%= image_tag "paleo-diet.png" %>
                <%= 'Paleo' %>
                <% when 'Primal' %>
                <%= image_tag "primal-diet.png" %>
                <%= 'Primal' %>
                <% when '' %>
                <div class='no-diet-type'></div>
                <%= 'Not specify' %>
                <% end %>
              </div>
              <div class="current-meal-plan-details">
                <h3><%= current_user.active_plan.created_at.strftime("%b %d, %Y") %></h3>
                <h5>Calories: <span class="meal-filter-info"><%= current_user.active_plan.calories %></span></h5>
                <h5>Allergies/ dislikes: <span class="meal-filter-info"><%= (current_user.active_plan.exclusions).split(',').join(', ').last((current_user.active_plan.exclusions).split(',').join(', ').length - 1) %></span></h5>
              </div>
            </div>
            <div class="progress-track">
              <h6>Meals cooked:</h6>
              <div class="progress mb-2">
                <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.meals_cooked_percent %>%" aria-valuenow="<%= current_user.active_plan.meals_cooked_percent %>" aria-valuemin="0" aria-valuemax="100">
                  <%= current_user.active_plan.meals_cooked_percent %>%
                </div>
              </div>
              <h6>Ingredients bought:</h6>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width:<%= current_user.active_plan.ingredients_bought_percent %>%" aria-valuenow="<%= current_user.active_plan.ingredients_bought_percent %>" aria-valuemin="0" aria-valuemax="100">
                  <%= current_user.active_plan.ingredients_bought_percent %>%
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div class="generate-new-plan d-flex justify-content-around">
          <%= link_to "Generate new meal plan", meal_plans_new_path, class: "btn btn-primary px-5"%>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="cooked-meal-container mx-3">
        <h2 class="text-center mb-4">Delivery Address</h2>
        <%= render "deliveries/form" %>
      </div>
    </div>
  </div>
</div>