config/routes.rb
Rails.application.routes.draw do
  get 'doses/index'
  get 'meal_plans/index'
  get 'meal_plans/show'
  get 'meal_plans/new'
  get 'meal_plans/create'
  get 'meals/show'
  get 'deliveries/new'
  post 'deliveries/create'
  get "shop/shopping"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meal_plans do
    resources :meals, only: [:show, :update]
    resources :doses, only: [:index]
    resources :shops, only: [:new, :create]
    resources :deliveries, only: [:new, :create]
  end
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
end

app/views/pages/home.html.erb
<div class="banner d-flex justify-content-center flex-column" style="background-image: url('<%= image_path "landing-01.png" %>');" id="landing">
  <div class="container">
    <h1>FoodOGood</h1>
    <h2>Meal Prep Made Easy</h2>
    <%= link_to "Get your meal plan now", new_meal_plan_path, class: "btn btn-secondary mt-3" %>
    <%= link_to "Learn more about us", "#info", class: "btn btn-primary mt-3" %>
  </div>
</div>
<div class="banner d-flex justify-content-end align-items-center flex-column" style="background-image: url('<%= image_path "landing-02.png" %>');" id="info">
  <div class="info-container">
    <h2 class="mb-4">Discover healthy meal plans to prepare.</h2>
    <p>
      Self-care in terms of food consumption is often compromised too easily for the sake of convenience. Continuously eating fast food can lead to undue health concerns that diminish quality of life. Our app help people plan out meals based on personal preferences. FoodOGood eliminates obstacles and time-consuming steps so you can effectively create a meal plan that suits your palette.
    </p>
  </div>
  <%= link_to "Get your meal plan now", new_meal_plan_path, class: "btn btn-secondary mt-3 igr-btn" %>
  <%= link_to raw("<i class='fas fa-chevron-down mb-3'></i>"), '#more' %>
</div>
<div class="banner d-flex justify-content-end align-items-center flex-column" style="background-image: url('<%= image_path "landing-03.png" %>');" id="more">
  <div class="info-container">
    <h2 class="mb-4">Stop eating junk food and feel better.</h2>
    <p>
      Save time and sustain a healthier lifestyle so you can better concentrate on work. In the process of changing eating habits, learn to appreciate cooking. Create weekly meal plans based on options that include diet type, caloric intake, allergies, and personal tastes.
    </p>
  </div>
  <%= link_to "Get your meal plan now", new_meal_plan_path, class: "btn btn-secondary mt-3 igr-btn" %>